### PR TITLE
Fix some bugs with task queue

### LINKED ISSUE #1383: The download process is not visible and the notification is not displayed correctly
### Steps to reproduce

cats
After updating to Github Action 2.0.0 (01/01/25 11:58 AM UTC) Commit: 9636aab5 two problems appeared
1) the process of downloading chapters is not visible, while the download is in progress (screen 2).
2) the notification does not work correctly, when chapters are downloading, the notification says “Preparation” throughout the entire time the chapters are downloading.

### Expected behavior

1) it should be visible that the chapter is in the process of loading or is waiting for its turn to be loaded
2) Instead of “Preparation,” the name of the currently loading chapter should be written.

### Actual behavior

1) the process of downloading or preparing for downloading is not visible
2) you can’t see which chapter is loading.

### LNReader version

Github Action 2.0.0 (01/01/25 11:58 AM UTC) Commit: 9636aab5

### Android version

Android 10

### Device

Realme C11 (2020)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Soopyboo32**
closes #1383

- Fixes the chapter download notification stuf on "Prepairing"
- Fixes the download spinner not showing in chapter list

### CODE REVIEW

File: src/services/ServiceManager.ts [hunk 1]
```diff
@@ -35,10 +35,11 @@ export type BackgroundTask =
...
   | { name: 'MIGRATE_NOVEL'; data: MigrateNovelData }
-  | {
-      name: 'DOWNLOAD_CHAPTER';
-      data: { chapterId: number; novelName: string; chapterName: string };
-    };
+  | DownloadChapterTask;
+export type DownloadChapterTask = {
+  name: 'DOWNLOAD_CHAPTER';
+  data: { chapterId: number; novelName: string; chapterName: string };
+};
```
Comment (Soopyboo32) [inline src/services/ServiceManager.ts:42]: This change should have been part of the first commit of the 2 but idk how to split single files up with command line and itll prob get squashed together anyway :shrug:

File: src/hooks/persisted/useDownload.ts [hunk 2]
```diff
@@ -1,19 +1,23 @@
...
-  const [queue] = useMMKVObject<BackgroundTask[]>(
+  const [queue] = useMMKVObject<QueuedBackgroundTask[]>(
     ServiceManager.manager.STORE_KEY,
   );
   const downloadQueue = useMemo(
-    () => queue?.filter(t => t.name === 'DOWNLOAD_CHAPTER') || [],
+    () => queue?.filter(t => t.task.name === 'DOWNLOAD_CHAPTER') || [],
     [queue],
-  );
+  ) as { task: DownloadChapterTask; meta: BackgroundTaskMetadata }[];
```
Comment (Soopyboo32) [inline src/hooks/persisted/useDownload.ts:20]: Some extra type saftey

**Comment by Soopyboo32** [comment]
afaik that happened b4 changes

**Review by nyagami — APPROVED** [review]
