### PR TITLE
Fix service manager down

### LINKED ISSUE #1373: Library update is broken
### Steps to reproduce

When trying to update a library using version Github Action 2.0.0 (29/12/24 06:00 AM UTC) Commit: d39dabef (Improve Task Queue), an error appears, while the previous one (Github Action 2.0.0 (27/12/24 03:17 PM UTC) Commit: e01cbefd) the library is updated without errors.

image

### Expected behavior

Updating the library should work

### Actual behavior

Can't update library

### LNReader version

Github Action 2.0.0 (29/12/24 06:00 AM UTC) Commit: d39dabef

### Android version

Android 10

### Device

Realme C11 (2020)

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with a source, I should be opening an issue in the [sources repository](https://github.com/lnreader/lnreader-sources/issues/new/choose).
- [X] I have updated the app to version **[2.0.0](https://github.com/lnreader/lnreader/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Soopyboo32**
`this` moment

fixes #1373

### CODE REVIEW

File: src/services/ServiceManager.ts [hunk 1]
```diff
@@ -96,7 +96,7 @@ export default class ServiceManager {
   setMeta(
     transformer: (meta: BackgroundTaskMetadata) => BackgroundTaskMetadata,
   ) {
-    let taskList = [...this.getTaskList()];
+    let taskList = [...ServiceManager.manager.getTaskList()];
```
Comment (Soopyboo32) [inline src/services/ServiceManager.ts:99]: oh wait i can rollback this part actually cus this is bound now

**Review by rajarsheechatterjee — APPROVED** [review]
